routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('student', 'StudentController');
Route::resource('matter', 'MatterController');
Route::resource('notes', 'NotesController');
Route::resource('assigned', 'AssignedController');

//php artisan route:list
//https://techhome-erta.com/

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/student2.blade.php
@extends('layouts.app')
@section('content')
    <h1>
        Hijos 
    </h1>
    <a href="{{ route('student.create') }}" class="btn btn-primary" role="button">Crear Nuevo Estudiante</a>
    <table class="table" style="margin-top:20px;">
            <thead class="thead-dark">
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Correo</th>
                      <th scope="col">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
    @foreach($students as $clave => $valor)
        <tr>
            <th> {{$valor['name']}}</th>
            <th>{{$valor['email']}}</th> 
            <th>
                <a href="{{ route('student.edit',$valor['id']) }}" class="btn btn-warning" role="button">editar</a>
                <a href="{{ route('student.show', $valor['id']) }}" class="btn btn-info" role="button">Ver Detalle</a>
                <a href="{{ route('student.destroy', $valor['id']) }}" class="btn btn-danger" role="button">Eliminar</a>
            </th> 
        </tr>
    @endforeach
                  </tbody>
  
    </table>
@endsection