routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('student', 'StudentController');
Route::resource('matter', 'MatterController');
Route::resource('notes', 'NotesController');
Route::resource('assigned', 'AssignedController');

//php artisan route:list
//https://techhome-erta.com/

app/Matter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Matter extends Model
{
    //
    protected $table = "matter";
    protected $fillable =  array('name',);
}

app/Http/Controllers/MatterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Matter;
class MatterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $materias = Matter::all();
        return view("matter.index",["materias"=>$materias]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view("matter.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $materia = new Matter;
        $materia->nombre = $request->input("nombre");
        $materia->save();
        return redirect()->route('matter.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $materia = Matter::find($id);
        return response()->json($materia);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/matter/create.blade.php
@extends('layouts.app')
@section('content')

<form action="{{ route('matter.store') }}" method="POST">
    @csrf
    <input type="text" name="nombre" >
    <input type="submit" name="guardar">
</form>

@endsection

resources/views/matter/index.blade.php
@extends('layouts.app')
@section('content')
    <h1>
        Materias 
    </h1>
    <a href="{{ route('matter.create') }}" class="btn btn-primary" role="button">Crear Nueva Materia</a>
    <table class="table" style="margin-top:20px;">
            <thead class="thead-dark">
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">accion</th>
                    </tr>
                  </thead>
                  <tbody>
            @foreach($materias as $clave => $valor)
                <tr>
                    <th> {{$valor['nombre']}}</th>
                    <th><a href="{{ route('matter.show',$valor['id'])}}">ver detalles</a></th>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection